# Lab Sheet : 2

In [2]:
import pandas as pd
import numpy as np
import os

In [2]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [7]:
os.getcwd()

'C:\\Users\\vijes\\OneDrive\\Desktop\\Jupyter\\ECE_Lab_ML'

# Exercise 1 :

In [13]:
data = pd.read_csv("C:/Users/vijes/Downloads/ML_s4_LAB/labsheet(2)/house_train (1).csv")
type(data)

pandas.core.frame.DataFrame

In [29]:
print("Number of rows and columns in the dataset : ")
data.shape

Number of rows and columns in the dataset : 


(1460, 81)

In [28]:
print("First 5 rows of the data : ")
data.head()

First 5 rows of the data : 


Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  
3   2006        WD        Abnorml     140000  
4   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [26]:
print("Summary of the data : ")
data.info

Summary of the data : 


<bound method DataFrame.info of         Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0        1          60       RL         65.0     8450   Pave   NaN      Reg   
1        2          20       RL         80.0     9600   Pave   NaN      Reg   
2        3          60       RL         68.0    11250   Pave   NaN      IR1   
3        4          70       RL         60.0     9550   Pave   NaN      IR1   
4        5          60       RL         84.0    14260   Pave   NaN      IR1   
...    ...         ...      ...          ...      ...    ...   ...      ...   
1455  1456          60       RL         62.0     7917   Pave   NaN      Reg   
1456  1457          20       RL         85.0    13175   Pave   NaN      Reg   
1457  1458          70       RL         66.0     9042   Pave   NaN      Reg   
1458  1459          20       RL         68.0     9717   Pave   NaN      Reg   
1459  1460          20       RL         75.0     9937   Pave   NaN      Reg   

     LandContour Ut

# Example :

In [32]:
a = list(range(100))
print(f"The space taken by the list is {a.__sizeof__()} in bytes")

The space taken by the list is 840 in bytes


In [36]:
import time as tm
s = tm.time()
a = list(range(1000000))
a = (a*2)
print("Time taken to multiply in a list = ", tm.time() - s)

Time taken to multiply in a list =  0.0358426570892334


In [38]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array)
print()
print("ndim : ", array.ndim)
print()
print("shape : ", array.shape)
print()
print("size : ", array.size)
print()
print("dtype : ", array.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

ndim :  2

shape :  (3, 3)

size :  9

dtype :  int32


In [40]:
a = array.T
print("Transpose of the array : ", a)

Transpose of the array :  [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [41]:
x = array.dot(a)
print("Matrix to matrix multiplication" , x)

Matrix to matrix multiplication [[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]


In [44]:
np.concatenate((array, a), axis = 1)

array([[1, 2, 3, 1, 4, 7],
       [4, 5, 6, 2, 5, 8],
       [7, 8, 9, 3, 6, 9]])

# Exercise 2 :

In [17]:
df = pd.read_csv("C:/Users/vijes/Downloads/ML_s4_LAB/labsheet(2)/concap[1] (1).xls")

In [19]:
# Reference coordinates for Washington, D.C.
washington_dc = np.array([38.89511, -77.03637])

# Extract capital names, country names, and their coordinates
capital_coords = df[["CapitalLatitude", "CapitalLongitude"]].to_numpy()
capital_names = df["CapitalName"].to_numpy()
country_names = df["CountryName"].to_numpy()

# Compute Euclidean distances from Washington, D.C.
distances = np.linalg.norm(capital_coords - washington_dc, axis=1)

# Get indices of the top 10 closest cities
closest_indices = np.argsort(distances)[:10]

# 1. Closest capital city to Washington, D.C.
closest_city = capital_names[closest_indices[0]]
closest_city_coords = capital_coords[closest_indices[0]]

# 2. Names of the countries of the top 10 closest capital cities
closest_countries = country_names[closest_indices]

# 3. NumPy array of coordinates of the top 10 closest cities
top_10_coords = capital_coords[closest_indices]

# Print results
print("Closest capital to Washington, D.C.:", closest_city, closest_city_coords)
print()
print("Countries of the top 10 closest capitals:", closest_countries)
print()
print("Coordinates of the top 10 closest capitals:\n", top_10_coords)


Closest capital to Washington, D.C.: Washington [ 38.883333 -77.      ]

Countries of the top 10 closest capitals: ['United States' 'US Minor Outlying Islands' 'Canada' 'Bahamas' 'Bermuda'
 'Cuba' 'Turks and Caicos Islands' 'Cayman Islands' 'Jamaica' 'Haiti']

Coordinates of the top 10 closest capitals:
 [[ 38.883333   -77.        ]
 [ 38.883333   -77.        ]
 [ 45.41666667 -75.7       ]
 [ 25.08333333 -77.35      ]
 [ 32.28333333 -64.783333  ]
 [ 23.11666667 -82.35      ]
 [ 21.46666667 -71.133333  ]
 [ 19.3        -81.383333  ]
 [ 18.         -76.8       ]
 [ 18.53333333 -72.333333  ]]


# Exercise 3 :

In [1]:
import numpy as np
random_array = np.random.randint(1, 51, size=(3, 4))
print("Original Array:")
print(random_array)
print()
print("Number of Dimensions (ndim):", random_array.ndim)
print()
print("Shape of the Array (shape):", random_array.shape)
print("\nTotal Number of Elements (size):", random_array.size)
print("\nData Type of the Elements (dtype):", random_array.dtype)
print("\nTranspose of the Array (T):")
print(random_array.T)

Original Array:
[[40 13  3  6]
 [33 26 28  6]
 [ 6 40 34  4]]

Number of Dimensions (ndim): 2

Shape of the Array (shape): (3, 4)

Total Number of Elements (size): 12

Data Type of the Elements (dtype): int32

Transpose of the Array (T):
[[40 33  6]
 [13 26 40]
 [ 3 28 34]
 [ 6  6  4]]


# Exercise 4 :

In [2]:
A = np.array([2, 4, 6, 8])
B = np.array([1, 3, 5, 7])
X = A + B
print("Addition (A + B):", X)
print()
X = A - B
print("Subtraction (A - B):", X)
print()
X = A * B
print("Multiplication (A * B):", X)
print()
X = A / B
print("Division (A / B):", X)

Addition (A + B): [ 3  7 11 15]

Subtraction (A - B): [1 1 1 1]

Multiplication (A * B): [ 2 12 30 56]

Division (A / B): [2.         1.33333333 1.2        1.14285714]


# Exercise 5 :

In [22]:
A = np.array([[1, 2, 3], [4, 5, 6]])
X = A + 5
print("Addition with 5:\n", X)
print()
# ii) Multiply each column by a different number using broadcasting: [2, 3, 4]
D = np.array([2, 3, 4])
X = A * D
print("Multiplication with [2, 3, 4]:\n", X)

Addition with 5:
 [[ 6  7  8]
 [ 9 10 11]]

Multiplication with [2, 3, 4]:
 [[ 2  6 12]
 [ 8 15 24]]


# Exercise 6 :

In [3]:
import numpy as np
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([15, 20, 25, 40, 55]) 
print(arr1>arr2,arr1<arr2,arr1==arr2)

[False False  True False False] [ True False False False  True] [False  True False  True False]


# Exercise 7 :

In [24]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(np.concatenate((A,B),axis=0))
print()
print(np.concatenate((A,B),axis=1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]


# Exercise 8:

In [25]:
arr = np.array([1, 2, 3, 4, 5, 6])
square_arr=np.square(arr)
print(square_arr)
print()
print(np.sqrt(arr))
print()
print(np.log(arr))

[ 1  4  9 16 25 36]

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


# Exercise 9:

In [26]:
import numpy as np
import random
random_integer = random.randint(10, 100)
random_matrix = np.random.rand(3, 3)
random_sample = np.random.normal(loc=50, scale=10, size=5)
original_array = [1, 2, 3, 4, 5, 6, 7, 8, 9]
shuffled_array = original_array[:]
random.shuffle(shuffled_array)
print("Random integer:", random_integer)
print()
print("3x3 random matrix:\n", random_matrix)
print()
print("Random sample from normal distribution:", random_sample)
print()
print("Shuffled array:", shuffled_array)

Random integer: 71

3x3 random matrix:
 [[0.65410112 0.35742007 0.29951751]
 [0.18086743 0.67781523 0.64309893]
 [0.371714   0.8326722  0.17736046]]

Random sample from normal distribution: [41.51172614 50.37730185 28.55462277 35.74748419 51.4454108 ]

Shuffled array: [1, 3, 5, 9, 4, 7, 8, 2, 6]


# Exercise 10:

In [27]:
import pandas as pd
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Age": [25, 30, 22, 35, 28],
    "Salary": [50000, 60000, 45000, 80000, 70000],
    "Department": ["HR", "IT", "Finance", "IT", "HR"]
}
df = pd.DataFrame(data)
print("First three rows:\n", df.head(3))
print("\nLast two rows:\n", df.tail(2))
print("\nSummary of numerical columns:\n", df.describe())
print("\nMaximum Salary:", df["Salary"].max())
print("Minimum Salary:", df["Salary"].min())
print("\nMean Age:", df["Age"].mean())
print("Median Age:", df["Age"].median())
print("\nStandard Deviation of Salary:", df["Salary"].std())
print("\nRandom sample of 2 rows:\n", df.sample(2))
filtered_df = df[df["Salary"] >= 50000]
print("\nDataFrame after removing rows where Salary < 50000:\n", filtered_df)
df["Salary"] = df["Salary"] * 1.10
print("\nSalary increased by 10%:\n", df)
df["Department"] = df["Department"].map(str.upper)
print("\nDepartment names in uppercase:\n", df)
df_dropped_age = df.drop(columns=["Age"])
print("\nDataFrame after dropping Age column:\n", df_dropped_age)
print("\nUnique department names:\n", df["Department"].unique())
print("\nEmployee count per department:\n", df["Department"].value_counts())
employees_to_check = ["Alice", "John", "David"]
existing_employees = {name: name in df["Name"].values for name in employees_to_check}
print("\nEmployee existence check:\n", existing_employees)
print("\nEmployees above 25 years old using loc:\n", df.loc[df["Age"] > 25])
print("\nEmployees above 25 years old using iloc:\n", df[df["Age"] > 25])
sorted_df = df.sort_values(by="Salary", ascending=False)
print("\nDataFrame sorted by Salary (descending):\n", sorted_df)
df["Salary Rank"] = df["Salary"].rank(ascending=False)
print("\nEmployees ranked by salary:\n", df)
bonus_data = {"Name": ["Alice", "Bob", "Charlie", "David", "Eva"], "Bonus": [5000, 7000, 4000, 9000, 8000]}
bonus_df = pd.DataFrame(bonus_data)
df = df.merge(bonus_df, on="Name")
print("\nDataFrame after adding Bonus column:\n", df)
df["Total Earnings"] = df["Salary"] + df["Bonus"]
print("\nTotal Earnings (Salary + Bonus):\n", df)
df["Adjusted Salary"] = df["Salary"] + [1000, 2000, 1500, 3000, 2500]
print("\nAdjusted Salary:\n", df)

First three rows:
       Name  Age  Salary Department
0    Alice   25   50000         HR
1      Bob   30   60000         IT
2  Charlie   22   45000    Finance

Last two rows:
     Name  Age  Salary Department
3  David   35   80000         IT
4    Eva   28   70000         HR

Summary of numerical columns:
              Age        Salary
count   5.000000      5.000000
mean   28.000000  61000.000000
std     4.949747  14317.821063
min    22.000000  45000.000000
25%    25.000000  50000.000000
50%    28.000000  60000.000000
75%    30.000000  70000.000000
max    35.000000  80000.000000

Maximum Salary: 80000
Minimum Salary: 45000

Mean Age: 28.0
Median Age: 28.0

Standard Deviation of Salary: 14317.821063276353

Random sample of 2 rows:
       Name  Age  Salary Department
3    David   35   80000         IT
2  Charlie   22   45000    Finance

DataFrame after removing rows where Salary < 50000:
     Name  Age  Salary Department
0  Alice   25   50000         HR
1    Bob   30   60000         IT
3